### ISSUE TITLE
Timestamp helpers

### ISSUE THREAD

**Issue by kdawgwilk** [elixir-protobuf/google-protos#8]
It would be nice to have some Timestamp helpers to convert to/from Elixir datetimes and `Google.Protobuf.Timestamp`

**Comment by whatyouhide** [comment]
Thanks for the issue and idea @kdawgwilk! I answered [here](https://github.com/elixir-protobuf/google-protos/pull/15#issuecomment-1221479545) on why I don't think this belongs in this library. Closing this issue now. Thank you so much! 💟
